// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_quantile_calc
List cpp_quantile_calc(DataFrame df, CharacterVector feature_cols);
RcppExport SEXP _SA25204160_cpp_quantile_calc(SEXP dfSEXP, SEXP feature_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type feature_cols(feature_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quantile_calc(df, feature_cols));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA25204160_cpp_quantile_calc", (DL_FUNC) &_SA25204160_cpp_quantile_calc, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA25204160(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
